site_name: docker-mailserver
site_description: A Dockerized mail server with a web interface for managing your email infrastructure.
site_url: https://jeboehm.github.io/docker-mailserver/
repo_name: jeboehm/docker-mailserver
repo_url: https://github.com/jeboehm/docker-mailserver
edit_uri: blob/main/docs/
remote_branch: gh-pages
theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.superfences
exclude_docs: |
  example-configs/**
  requirements.txt

nav:
  - Welcome: README.md
  - Quick Start:
      - installation.md
      - upgrade.md
  - Configuration:
      - configuration/environment-variables.md
      - configuration/dns-configuration.md
      - configuration/external-mysql.md
      - configuration/relayhost.md
      - configuration/local-address-extension.md
      - configuration/php-sessions.md
      - configuration/reverse-proxy.md
      - configuration/roundcube.md
      - configuration/tls.md
  - Administration:
      - administration/dashboard.md
      - administration/manage-domains.md
      - administration/manage-users.md
      - administration/manage-aliases.md
      - administration/manage-fetchmail.md
      - administration/dkim-signing.md
      - administration/dns-validation-wizard.md
  - Recipes:
      - Docker:
          - Traefik Reverse Proxy: https://github.com/jeboehm/docker-mailserver/tree/main/docs/example-configs/compose/traefik-reverse-proxy
      - Kubernetes:
          - External Database and HTTPS Ingress: https://github.com/jeboehm/docker-mailserver/tree/main/docs/example-configs/kustomize/external-db-and-https-ingress
  - Development:
      - development/architecture.md
      - development/development.md
  - Issues: https://github.com/jeboehm/docker-mailserver/issues
