site_name: docker-mailserver
site_description: A Dockerized mail server with a web interface for managing your email infrastructure.
site_url: https://jeboehm.github.io/docker-mailserver/
repo_name: jeboehm/docker-mailserver
repo_url: https://github.com/jeboehm/docker-mailserver
edit_uri: blob/main/docs/
remote_branch: gh-pages
theme: readthedocs
markdown_extensions:
  - admonition
  - pymdownx.superfences
exclude_docs: |
  example-configs/**
  requirements.txt

nav:
  - Welcome: README.md
  - Quick Start:
      - installation.md
      - upgrade.md
  - Configuration:
      - environment-variables.md
      - dns-configuration.md
      - external-mysql.md
      - relayhost.md
      - local-address-extension.md
      - php-sessions.md
      - reverse-proxy.md
      - roundcube.md
      - tls.md
  - Administration:
      - manage-domains.md
      - manage-users.md
      - manage-aliases.md
      - manage-fetchmail.md
      - dkim-signing.md
  - Recipes:
      - Docker:
          - Traefik Reverse Proxy: https://github.com/jeboehm/docker-mailserver/tree/main/docs/example-configs/compose/traefik-reverse-proxy
      - Kubernetes:
          - External Database and HTTPS Ingress: https://github.com/jeboehm/docker-mailserver/tree/main/docs/example-configs/kustomize/external-db-and-https-ingress
  - Development:
      - architecture.md
      - development.md
  - Issues: https://github.com/jeboehm/docker-mailserver/issues
