---

services:
  mda:
    ports:
      - "0.0.0.0:143:143"
      - "0.0.0.0:993:993"
      - "0.0.0.0:110:110"
      - "0.0.0.0:995:995"

  mta:
    ports:
      - "0.0.0.0:25:25"
      - "0.0.0.0:587:587"
    # Uncomment to use SSL encrypted mail submission
    #  - "0.0.0.0:465:465"

  web:
    ports:
      - "0.0.0.0:81:80"
