name: Test YAML manifests
on:
  pull_request:
    paths:
      - "test/pajv/**"
      - "deploy/**"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  test_kustomize_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run kustomize build
        run: |
          make .env
          kustomize build .
  test_yaml_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: test/pajv/package-lock.json
      - name: Install packages
        run: |
          cd test/pajv
          npm install
      - name: Run yaml schema test
        run: |
          cd test/pajv
          ./run-tests.sh
