name: Test YAML manifests
on:
  pull_request:
    paths:
      - "test/pajv/**"
      - "deploy/**"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  test_kustomize_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - name: Run kustomize build
        run: |
          make .env
          kustomize build .
  test_yaml_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: test/pajv/package-lock.json
      - name: Install packages
        run: |
          cd test/pajv
          npm install
      - name: Run yaml schema test
        run: |
          cd test/pajv
          ./run-tests.sh
