name: Test YAML manifests
on:
  pull_request:
    paths:
      - "test/pajv/**"
      - "deploy/**"
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true
jobs:
  test_kustomize_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - name: Run kustomize build
        run: |
          make .env
          kustomize build .
  test_yaml_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: test/pajv/package-lock.json
      - name: Install packages
        run: |
          cd test/pajv
          npm install
      - name: Run yaml schema test
        run: |
          cd test/pajv
          ./run-tests.sh
